/*
Copyright (c) 2003-2017 Christopher M. Kohlhoff (chris at kohlhoff dot com) under the Boost v1 license:

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <boost/asio.hpp>
#include <string>
#include <vector>
#include <boost/thread/thread.hpp>
#include <boost/bind.hpp>
#include <boost/noncopyable.hpp>
#include <boost/shared_ptr.hpp>
#include <compsky/macros/likely.hpp>
#include "connection.hpp"

// Example usage: compsky::server::Server<6>(port_id).run();

namespace compsky {
namespace server {

template<size_t thread_pool_size_,  class RequestHandler>
class server : private boost::noncopyable {
public:
	explicit server(const std::string& port)
	, signals_(io_context_)
	, acceptor_(io_context_)
	, new_connection_()
	{
		// Register to handle the signals that indicate when the server should exit.
		// It is safe to register for the same signal multiple times in a program,
		// provided all registration for the specified signal is made through Asio.
		signals_.add(SIGINT);
		signals_.add(SIGTERM);
	  #ifdef SIGQUIT
		signals_.add(SIGQUIT);
	  #endif
		signals_.async_wait(boost::bind(&server::handle_stop, this));
		
		boost::asio::ip::tcp::resolver resolver(io_context_);
		boost::asio::ip::tcp::endpoint endpoint = *resolver.resolve("0.0.0.0", port).begin();
		acceptor_.open(endpoint.protocol());
		acceptor_.set_option(boost::asio::ip::tcp::acceptor::reuse_address(true));
		acceptor_.bind(endpoint);
		acceptor_.listen();

		start_accept();
	}

	/// Run the server's io_context loop.
	void run(){
		std::array<boost::shared_ptr<boost::thread>, thread_pool_size_> threads;
		for (auto i = 0;  i < thread_pool_size_;  ++i){
			boost::shared_ptr<boost::thread> thread(new boost::thread(
				boost::bind(&boost::asio::io_context::run, &io_context_)));
			threads[i] = thread;
		}
		for (auto i = 0;  i < thread_pool_size_;  ++i)
			threads[i]->join();
	}

private:
	/// Initiate an asynchronous accept operation.
	void start_accept(){
		new_connection_.reset(new connection(io_context_, request_handler_));
		acceptor_.async_accept(
			new_connection_->socket(),
			boost::bind(
				&server::handle_accept,
			   this,
				boost::asio::placeholders::error
			)
		);
	}

	/// Handle completion of an asynchronous accept operation.
	void handle_accept(const boost::system::error_code& e){
		if (likely(not e))
			new_connection_->start();
		start_accept();
	}

	/// Handle a request to stop the server.
	void handle_stop(){
		io_context_.stop();
	}

	/// The io_context used to perform asynchronous operations.
	boost::asio::io_context io_context_;

	/// The signal_set is used to register for process termination notifications.
	boost::asio::signal_set signals_;

	/// Acceptor used to listen for incoming connections.
	boost::asio::ip::tcp::acceptor acceptor_;

	/// The next connection to be accepted.
	boost::shared_ptr<connection> new_connection_;

	/// The handler for all incoming requests.
	RequestHandler request_handler_;
};

} // namespace server
} // namespace compsky
