version: 2
general:
  artifacts:
    - "packages"
jobs:
  build_debian10:
    docker:
      - image: debian:buster

    steps:
      - checkout
      - run:
          name: Install SQL Client Dev
          command: 'apt update  &&  apt install -y mariadb-client default-libmysqlclient-dev qt5-default libqt5widgets5'
      - run:
          name: Install sudo
          command: 'apt update  &&  apt install -y sudo  &&  rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt update  &&  apt install -y gcc g++'
      - run:
          name: Install CMake
          command: 'apt update  &&  sudo apt install -y cmake'
      - run:
          name: Generate build files
          command: 'mkdir build  &&  cd build  &&  cmake .. -DMYSQL_UNDER_DIR=/usr/include/mysql -DMYSQL_UNDER_DIR_OVERRIDE=1 -DBUILD_PACKAGES=1 -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=$(dpkg --print-architecture)'
      - run:
          name: Build
          command: 'cmake --build build'
      - run:
          name: Create Packages
          command: 'cd build  &&  cpack' # 'cpack -B packages' is the proper option, but it hangs during 'Create package' stage. Instead, have to move files afterwards.
      - run:
          name: Move Packages to Artifact Storage
          command: 'mkdir packages  &&  mv build/pkg/*.deb packages/'
      - store_artifacts:
          path: "packages"

  build_macos:
    macos:
      xcode: 10 # Doesn't matter, don't need xcode, but specified only because CircleCI ignores the 'macos:' field otherwise
    steps:
      - checkout
      - run:
          name: Install SQL Client Dev
          command: 'brew update  &&  brew install -y mariadb-client default-libmysqlclient-dev qt5-default libqt5widgets5'
      - run:
          name: Install sudo
          command: 'brew install -y sudo  &&  rm -rf /var/lib/brew/lists/*'
      - run:
          name: Install GCC
          command: 'brew install -y gcc g++'
      - run:
          name: Install CMake
          command: 'sudo brew install -y cmake'
      - run:
          name: Generate build files
          command: 'mkdir build  &&  cd build  &&  cmake .. -DMYSQL_UNDER_DIR=/usr/include/mysql -DMYSQL_UNDER_DIR_OVERRIDE=1 -DBUILD_PACKAGES=1 -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=$(dpkg --print-architecture)'
      - run:
          name: Build
          command: 'cmake --build build'
      - run:
          name: Create Packages
          command: 'cd build  &&  cpack' # 'cpack -B packages' is the proper option, but it hangs during 'Create package' stage. Instead, have to move files afterwards.
      - run:
          name: Move Packages to Artifact Storage
          command: 'mkdir packages  &&  mv build/pkg/*.deb packages/'
      - store_artifacts:
          path: "packages"

workflows:
  version: 2
  build:
    jobs:
      - build_debian10
      - build_macos
