version: 2
general:
  artifacts:
    - "packages"
jobs:
  build:
    docker:
            - image: debian:buster

    steps:
      - checkout
      - run:
          name: Install SQL Client Dev
          command: 'apt update  &&  apt install -y mariadb-client default-libmysqlclient-dev qt5-default libqt5widgets5'
      - run:
          name: Install sudo
          command: 'apt update  &&  apt install -y sudo  &&  rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt update  &&  apt install -y gcc g++'
      - run:
          name: Install CMake
          command: 'apt update  &&  sudo apt install -y cmake'
      - run:
          name: Generate build files
          command: 'mkdir build  &&  cd build  &&  cmake .. -DMYSQL_UNDER_DIR=/usr/include/mysql -DMYSQL_UNDER_DIR_OVERRIDE=1'
